prefix acl: <http://www.w3.org/ns/auth/acl#> 
prefix foaf: <http://xmlns.com/foaf/0.1/> 
prefix kds: <http://knowledgelinks.io/ns/data-structures/> 
prefix kdr: <http://knowledgelinks.io/ns/data-resources/> 
prefix obi: <https://w3id.org/openbadges#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix schema: <https://schema.org/> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT *
{
GRAPH <http://knowledgelinks.io/ns/application-framework/>
{
  SELECT (CONCAT('{"application":{',GROUP_CONCAT(?oj; SEPARATOR=','),'}}') AS ?app)
  {
    {
      SELECT ?klapp ?p  (GROUP_CONCAT(?ojf; SEPARATOR=',') AS ?oja)
                    {
                      SELECT ?klapp ?p ?o (CONCAT(IF(isblank(?o),'{','"'),GROUP_CONCAT(?oj; SEPARATOR=','),IF(isblank(?o),'}','"')) AS ?ojf)
                                    {
                                      {
                                        SELECT ?klapp ?p ?o ?bn_ ?p1_  (GROUP_CONCAT(?o1j; SEPARATOR=',') AS ?o1jf)
                                                      {
                                                        ?klapp a kds:Application .
                                                        ?klapp ?p ?o .
                                                        BIND(IF(ISBLANK(?o),?o,"") AS ?bn ).
                                                        OPTIONAL {
                                                          ?bn ?p1 ?o1 .
                                                        }
                                                        BIND(IF(bound(?o1),CONCAT('"',REPLACE(STR(?o1),"^(.*[#/])", ""),'"'),"") AS ?o1j)
                                                        BIND(IF(BOUND(?p1),?p1,"") AS ?p1_) .
                                                        BIND(IF(BOUND(?bn),?bn,"") AS ?bn_).
                                                      }
                                                      GROUP BY ?klapp ?p ?o ?bn_ ?p1_ 
                                      }
                                      BIND(IF(CONTAINS(?o1jf,'","'),true,false) AS ?bracket)
                                      BIND(IF(isblank(?o),CONCAT('"',REPLACE(STR(?p1_),"^(.*[#/])", ""),'":',IF(?bracket,'[',""),?o1jf,IF(?bracket,']',"")),?o) AS ?oj)
                                    }
                                    GROUP BY ?klapp ?p ?o 
                    }
                    GROUP BY ?klapp ?p 
    }
    BIND(IF(CONTAINS(?oja,'},{'),true,false) AS ?bracket)
    #BIND(CONCAT(IF(?bracket,'[',""),?oja,IF(?bracket,']',"")) AS ?oj)
    BIND(CONCAT('"',REPLACE(STR(?p),"^(.*[#/])", ""),'":',IF(?bracket,'[',""),?oja,IF(?bracket,']',"")) AS ?oj)
  }


								  			
}
}



