{{ prefix }}

SELECT (CONCAT('{',GROUP_CONCAT(?sJ;SEPARATOR=','),'}') AS ?itemJson)
{
  SELECT  (CONCAT('"',STR(?s),'":{',GROUP_CONCAT(?pJ;SEPARATOR=','),'}') AS ?sJ)
  {
    {
      SELECT DISTINCT ?s ?p (GROUP_CONCAT(?oV; SEPARATOR=',') AS ?oJ) (COUNT(?p) AS ?oC)
      {
      	{
      		SELECT DISTINCT ?s ?p ?o
		      {
		        {{ query }}
		        
		        FILTER(!(
		                  STRSTARTS(STR(?p), "http://fedora.info/definitions/v4/")||
		                  STRSTARTS(STR(?o), "http://fedora.info/definitions/v4/")||
		                  STRSTARTS(STR(?o), "http://www.w3.org/ns/ldp#Container")||
		                  STRSTARTS(STR(?o), "http://www.jcp.org/jcr/")||
		                  STRSTARTS(STR(?p), "http://www.w3.org/ns/ldp#Container")||
		                  STRSTARTS(STR(?p), "http://www.w3.org/ns/ldp#RDFSource")||
		                  STRSTARTS(STR(?o), "http://www.w3.org/ns/ldp#RDFSource")||
		                  STRSTARTS(STR(?o), "http://www.jcp.org/jcr/")))
		      }
		    }
		    BIND(IF(datatype(?o)=xsd:string||isiri(?o),true,false) AS ?quotes) .
		    BIND(CONCAT(IF(?quotes,'"',""),STR(?o),if(?quotes,'"',"")) AS ?oV) .
		  }    
      GROUP BY ?s ?p
    }
    BIND(CONCAT('"',STR(?p),'":',
                IF(?oC>1,"[",""),
                STR(?oJ),
                IF(?oC>1,"]","")) AS ?pJ)
  }
  GROUP BY ?s
}