prefix acl: <http://www.w3.org/ns/auth/acl#> 
prefix foaf: <http://xmlns.com/foaf/0.1/> 
prefix kds: <http://knowledgelinks.io/ns/data-structures/> 
prefix kdr: <http://knowledgelinks.io/ns/data-resources/> 
prefix obi: <https://w3id.org/openbadges#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix schema: <https://schema.org/> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT (CONCAT('{',GROUP_CONCAT(?jVal; SEPARATOR=','),'}') As ?appForms)
{
GRAPH <http://knowledgelinks.io/ns/application-framework/>
{
  		SELECT ?klForms (CONCAT('"',REPLACE(STR(?klForms),"^(.*[#/])", ""),'":{',GROUP_CONCAT(?jsonVal; SEPARATOR=','),'}') AS ?jVal)
        {
          {
            SELECT ?klForms ?p (CONCAT('"properties":[',GROUP_CONCAT(?propJ; SEPARATOR=','),']') AS ?jsonVal)
            {
              {
                SELECT  ?klForms ?p ?o ?bn ?property ?fieldOrder (CONCAT('{"className":"',REPLACE(STR(?propClass),"^(.*[#/])", ""),'","classUri":"',STR(?propClass),'",',GROUP_CONCAT(?o1j; SEPARATOR=','),'}') AS ?propJ)
                {
                  {
                    SELECT ?klForms ?p ?o ?bn ?property ?propClass ?fieldOrder (CONCAT('"',REPLACE(STR(?p1),"^(.*[#/])", ""),'":{',GROUP_CONCAT(?o2jfao; SEPARATOR=","),'}') AS ?o1j)
                    {
                      {
                        SELECT ?klForms ?p ?o ?bn ?property ?propClass ?fieldOrder ?p1 ?o1 ?bn2 ?p2 (GROUP_CONCAT(?o2j; SEPARATOR=",") AS ?o2jf)
                        {
                          {
                            SELECT ?klForms ?p ?o ?bn ?property ?propClass ?fieldOrder ?p1 ?o1 ?bn2 ?p2 ?o2 (GROUP_CONCAT(?p4; SEPARATOR=",") AS ?o3jf)
                                {
                                  {
                                    SELECT DISTINCT ?klForms ?p ?o ?bn ?property ?fieldOrder ?propClass ?p1 ?o1 ?bn2 ?p2 ?o2 ?bn3 ?p3 ?o3j1 
                                    {
                                      {
                                        {
                                          { 
                                            ?klForms a kds:FormClass .
                                            ?klForms ?p ?o .
                                            BIND(IF(ISBLANK(?o),?o,"") AS ?bn ).
                                            ?bn kds:propName ?property . 
                                            ?bn kds:formFieldOrder ?fieldOrder .
                                            OPTIONAL {?bn kds:classUri ?classUri } .
                                            ?property rdfs:domain ?domain .
                                            BIND(COALESCE(?classUri,?domain) AS ?propClass) .
                                            FILTER((bound(?classUri) && ?domain = ?classUri) || !(bound(?classUri)))
                                          } .
                                          ?property ?p1 ?o1 .
                                          BIND(IF(ISBLANK(?o1),?o1,"") AS ?bn2 ).
                                          OPTIONAL {
                                            {
                                              ?bn2 kds:appliesTo ?propClass .
                                              ?bn2 ?p2 ?o2 .
                                            } UNION {
                                              OPTIONAL {
                                                ?bn2 kds:appliesTo ?a1 .
                                                BIND(?bn2 AS ?found) .
                                              } .
                                              ?bn2 ?p2 ?o2 .
                                              FILTER(!(bound(?found)))
                                            }
                                          } .
                                        } 
                                        FILTER(!(bound(?bn)&&(!(bound(?p2)))))
                                      }
                                      BIND(IF(ISBLANK(?o2),?o2,"") AS ?bn3 ).
                                      OPTIONAL {
                                        ?bn3 ?p3 ?o3
                                      }
                                      BIND(CONCAT('"',REPLACE(REPLACE(REPLACE(STR(?o3),"\n",""),"\t",""),"  "," "),'"') AS ?o3j1) .

                                    }

                                  }
                                  BIND(IF(!(bound(?o3j1)),"",?o3j1) AS ?o3j) .
                                  BIND(IF(?o3j="","",?bn3) AS ?bn4) .
                                  BIND(IF(?o3j="","",CONCAT('"',REPLACE(STR(?p3),  "^(.*[#/])", ""),'":',?o3j)) AS ?p4)

                                }
                                GROUP BY ?klForms ?p ?o ?bn ?property ?propClass ?fieldOrder ?p1 ?o1 ?bn2 ?p2 ?o2 
                          }
                          BIND(IF(isBlank(?o2),CONCAT("{",?o3jf,"}"),CONCAT('"',STR(?o2),'"')) AS ?o2j)
                        }
                        GROUP BY ?klForms ?p ?o ?bn ?property ?propClass ?fieldOrder ?p1 ?o1 ?bn2 ?p2
                      }
                      BIND(IF((STRSTARTS(?o2jf,"{")&&CONTAINS(?o2jf,"},{"))||(!(STRSTARTS(?o2jf,"{"))&&CONTAINS(?o2jf,'","')),true,false) AS ?array) .
                      BIND(CONCAT(IF(?array,"[",""),?o2jf,IF(?array,"]","")) AS ?o2jfa) .
                      BIND(CONCAT('"',REPLACE(STR(?p2),  "^(.*[#/])", ""),'":',?o2jfa)  AS ?o2jfao)
                    }
                    GROUP BY ?klForms ?p ?o ?bn ?property ?fieldOrder ?propClass ?p1 
                  } UNION {
                    
                    SELECT * 
                    {
                    	{
                    		#Get the non-blank node hasProperty properties
		                    SELECT DISTINCT ?klForms ?p ?o ?bn ?property ?propClass ?o1j ?fieldOrder   #(CONCAT('{',GROUP_CONCAT(CONCAT(?subProp,':',?subObj); SEPARATOR=','),'}') AS ?valObject)
		                    {
		                      ?klForms a kds:FormClass .
		                      ?klForms ?p ?o .
		                      BIND(IF(ISBLANK(?o),?o,"") AS ?bn ).
		                      ?bn kds:propName ?property .
		                      ?bn kds:formFieldOrder ?fieldOrder .
		                      OPTIONAL {?bn kds:classUri ?classUri } .
		                      ?property rdfs:domain ?domain .
		                      BIND(COALESCE(?classUri,?domain) AS ?propClass) .	
		                      ?bn ?p1 ?o1 .
		                      FILTER(!(ISBLANK(?o1)))
		                      FILTER(!(kds:classUri=?p1))
		                      BIND(IF(datatype(?o1)=xsd:string||isIRI(?o1),true,false) AS ?quotes) 
		                      BIND(CONCAT('"',REPLACE(STR(?p1),"^(.*[#/])", ""),'":',IF(?quotes,'"',''),STR(?o1),IF(?quotes,'"','')) AS ?o1j)
		                    }
		                  } UNION {
		                  	#Get the blank node hasProperty properties
		                  	SELECT ?klForms ?p ?o ?bn ?property ?propClass ?o1j ?fieldOrder
												{
												  {
				  									SELECT ?klForms ?p ?o ?bn ?property ?fieldOrder ?domain ?propClass ?p1 (CONCAT('[',GROUP_CONCAT(CONCAT('{',?o2jf,'}'); SEPARATOR=','),']') AS ?o2ja) 
				  									{
				                      {
				  											SELECT ?klForms ?p ?o ?bn ?property ?fieldOrder ?domain ?propClass ?p1 ?o1 (GROUP_CONCAT(?o2j; SEPARATOR=',') AS ?o2jf)
													  		{
										              {
										                SELECT DISTINCT ?klForms ?p ?o ?bn ?property ?fieldOrder ?domain ?propClass ?p1 ?o1 ?p2 ?o2 (CONCAT('{',GROUP_CONCAT(?o3j; SEPARATOR=','),'}') AS ?o3jf)
										                {
								                      ?klForms a kds:FormClass .
								                      ?klForms ?p ?o .
								                      BIND(IF(ISBLANK(?o),?o,"") AS ?bn ).
								                      ?bn kds:propName ?property .
								                      ?bn kds:formFieldOrder ?fieldOrder .
								                      OPTIONAL {?bn kds:classUri ?classUri } .
								                      ?property rdfs:domain ?domain .
								                      BIND(COALESCE(?classUri,?domain) AS ?propClass) .	
								                      ?bn ?p1 ?o1 .
								                      FILTER(ISBLANK(?o1))
								                      FILTER(!(kds:classUri=?p1))
								                      ?o1 ?p2 ?o2 .
								                      BIND (IF(isBlank(?o2),?o2,"") AS ?bn2)
								                      OPTIONAL {
								                        ?bn2 ?p3 ?o3 .
								                      } .
								                      BIND(IF(bound(?o3),CONCAT('"',REPLACE(STR(?p3),"^(.*[#/])", ""),'":"',REPLACE(STR(?o3),"^(.*[#/])", ""),'"'),"") AS ?o3j)
								                  }
												  				GROUP BY ?klForms ?p ?o ?bn ?property ?fieldOrder ?domain ?propClass ?p1 ?o1 ?p2 ?o2
							                  }
							                  BIND(CONCAT('"',REPLACE(STR(?p2),"^(.*[#/])", ""),'":',IF(ISBLANK(?o2),?o3jf,CONCAT('"',STR(?o2),'"'))) AS ?o2j)
							                }
												  		GROUP BY ?klForms ?p ?o ?bn ?property ?fieldOrder ?domain ?propClass ?p1 ?o1
                            }
                          }
		         							GROUP BY ?klForms ?p ?o ?bn ?property ?fieldOrder ?domain ?propClass ?p1
		                    }
		                    BIND(CONCAT('"',REPLACE(STR(?p1),"^(.*[#/])", ""),'":',?o2ja) AS ?o1j)
	                 		}
		                  }
		                }
                  } UNION {
                    #Pull in class related details
                    SELECT ?klForms ?p ?o ?bn ?property ?fieldOrder ?propClass (CONCAT('"classInfo":{',GROUP_CONCAT(?p1j; SEPARATOR=','),'}') AS ?o1j)
                    {
                      {
                        SELECT ?klForms ?p ?o ?bn ?property ?fieldOrder ?propClass ?p1 (GROUP_CONCAT(?o1a; SEPARATOR=",") AS ?o1j)
                        {
                          {
                            SELECT ?klForms ?p ?o ?bn ?property ?fieldOrder ?propClass ?p1 ?o1 (GROUP_CONCAT(?p2j; SEPARATOR=",") AS ?p2jf)
                            {
                              {
                                SELECT ?klForms ?p ?o ?bn ?property ?fieldOrder ?propClass ?p1 ?o1 ?bn1 ?p2o (GROUP_CONCAT(?o2s; SEPARATOR=",") AS ?o2ja)
                                {
                                    SELECT DISTINCT ?klForms ?p ?o ?bn ?property ?fieldOrder ?propClass ?p1 ?o1 ?bn1 ?p2o ?o2s # (GROUP_CONCAT(?o2s; SEPARATOR=",") AS ?o2ja)
                                    {
                                      ?klForms a kds:FormClass .
                                      ?klForms ?p ?o .
                                      BIND(IF(ISBLANK(?o),?o,"") AS ?bn ).
                                      ?bn kds:propName ?property .
                                      ?bn kds:formFieldOrder ?fieldOrder .
                                      OPTIONAL {?bn kds:classUri ?classUri } .
                                      ?property rdfs:domain ?domain .
                                      BIND(COALESCE(?classUri,?domain) AS ?propClass) .
                                      ?propClass ?p1 ?o1 .
                                      FILTER(?p1=kds:classSecurity||?p1=kds:primaryKey) .
                                      BIND(IF(ISBLANK(?o1),?o1,"") AS ?bn1 ).
                                      OPTIONAL {
                                        ?bn1 ?p2 ?o2
                                      } .
                                      BIND(IF(bound(?o2),CONCAT('"',STR(?o2),'"'),"") AS ?o2s) .
                                      BIND(IF(bound(?p2),CONCAT('"',REPLACE(STR(?p2),  "^(.*[#/])", ""),'"'),"") AS ?p2o)
                                    }
                                  }
                                  GROUP BY ?klForms ?p ?o ?bn ?property ?fieldOrder ?propClass ?p1 ?o1 ?bn1 ?p2o
                                }
                                BIND(IF(CONTAINS(?o2ja,'","'),CONCAT('[',?o2ja,']'),?o2ja) AS ?o2jaf) .
                                BIND(IF(?p2o='"keyCombo"'||?p2o='',?o2jaf,CONCAT(?p2o,':',?o2jaf)) AS ?p2j)
                              }
                              GROUP BY ?klForms ?p ?o ?bn ?property ?fieldOrder ?propClass ?p1 ?o1
                          }
                          BIND(IF(STRSTARTS(?p2jf,"[")||?p2jf='',?p2jf,CONCAT("{",?p2jf,"}")) AS ?o1p)
                          BIND(IF(isBlank(?o1),?o1p,CONCAT('"',STR(?o1),'"')) AS ?o1a)
                        }
                        GROUP BY ?klForms ?p ?o ?bn ?property ?fieldOrder ?propClass ?p1
                      }
                      BIND(CONCAT('"',REPLACE(STR(?p1),  "^(.*[#/])", ""),'":',IF(CONTAINS(?o1j,"},{"),CONCAT('[',?o1j,']'),?o1j)) AS ?p1j) .
                    }
                    GROUP BY ?klForms ?p ?o ?bn ?property ?fieldOrder ?propClass
                  }

                }
                GROUP BY ?klForms ?p ?o ?bn ?property ?propClass ?fieldOrder
                ORDER BY ?klForms ?fieldOrder ?property  
              }
            }
            GROUP BY ?klForms ?p
            ORDER BY ?klForms ?fieldOrder ?property
          } UNION {
            SELECT ?klForms ?p ?jsonVal
  					{
              {
  							SELECT ?klForms ?p (GROUP_CONCAT(?o_o; SEPARATOR=",") AS ?oa)
  							{
                  {
  									SELECT ?klForms ?p ?o   (GROUP_CONCAT(?j1; SEPARATOR=",") AS ?ja)
  									{
                      {
												SELECT ?klForms ?p ?o ?bn_ ?p1_  (GROUP_CONCAT(?j1o; SEPARATOR=",") AS ?j1a)
  											{
                        	{
  													SELECT DISTINCT ?klForms ?p ?o ?bn_ ?p1_ ?o1_ (GROUP_CONCAT(?j2_; SEPARATOR=",") AS ?j2)
                            {
                              ?klForms a kds:FormClass .
                              ?klForms ?p ?o .
                              BIND(IF(ISBLANK(?o),?o,"") AS ?bn ).
                              FILTER (!(kds:hasProperty=?p)).
                              OPTIONAL {
                                ?bn ?p1 ?o1
                                BIND(IF(ISBLANK(?o1),?o1,"") AS ?bn2 ).
                                OPTIONAL {
                                  ?bn2 ?p2 ?o2
                                }
                              } .
                              BIND(IF(bound(?bn),?bn,'') AS ?bn_) .
                              BIND(IF(bound(?p1),?p1,'') AS ?p1_) .
                              BIND(IF(bound(?o1),?o1,'') AS ?o1_) .
                              BIND(IF(bound(?p2),?p2,'') AS ?p2_) .
                              BIND(IF(bound(?o2),CONCAT('"',REPLACE(STR(?p2),  "^(.*[#/])", ""),'":"',STR(?o2),'"'),"") AS ?j2_) . 
                          	}
  													GROUP BY ?klForms ?p ?o ?bn_ ?p1_ ?o1_ 
          			  			  }
         						  		BIND(REPLACE(IF(isBlank(?o1_)&&CONTAINS(?j2,","),CONCAT("{",?j2,"}"),IF(ISBLANK(?o1_),?j2,CONCAT('"',STR(?o1_),'"'))),'""','') AS ?j1o)
         								}
  											GROUP BY ?klForms ?p ?o ?bn_ ?p1_
                      }
         					  	BIND(IF((STRSTARTS(?j1a,'{')&&CONTAINS(?j1a,'},{'))||(!(STRSTARTS(?j1a,'{'))&&CONTAINS(?j1a,'","')),true,false) AS ?bracket) .
  							  		BIND(IF(ISBLANK(?bn_),CONCAT('"',REPLACE(STR(?p1_),  "^(.*[#/])", ""),'":',IF(?bracket,'[',''),?j1a,IF(?bracket,']','')),'') AS ?j1)
         						}
  									GROUP BY ?klForms ?p ?o
                  }        
                  BIND(IF(ISBLANK(?o),CONCAT('{',?ja,'}'),CONCAT('"',STR(?o),'"')) AS ?o_o)
                }
  							GROUP BY ?klForms ?p
              }
         			BIND(IF(STRSTARTS(?oa,"{")&&CONTAINS(?oa,'},{')&&?p!=kds:formInstructions,true,false) AS ?bracket)
              BIND(CONCAT('"',REPLACE(STR(?p),"^(.*[#/])", ""),'":',IF(?bracket,'[',''),?oa,IF(?bracket,']','')) AS ?jsonVal)
         		}
          }
        }
        GROUP BY ?klForms
  	
}
}
ORDER BY ?klForms ?fieldOrder ?property ?propClass



